package uai_biblioteca;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class loginAdm extends javax.swing.JFrame {

    Conexion cn;
    String nombre;
    static int idResponsable = 1;
    Icon usrVal, usrNVal, usrDen;
    
     public loginAdm() throws Exception {
        initComponents();
        usrVal= new ImageIcon(getClass().getResource("/img/userVal.png"));
        usrNVal= new ImageIcon(getClass().getResource("/img/userNoValido.png"));
        usrDen= new ImageIcon(getClass().getResource("/img/userError.png"));
        cn=new Conexion();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public Image getIconImage(){
      Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/libros.png"));
      return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tFPass = new org.edisoncor.gui.passwordField.PasswordFieldRoundBackground();
        tFUsuario = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/palomita.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adm.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 142, 110));

        tFPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tFPass.setDescripcion("Contraseña");
        tFPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPassActionPerformed(evt);
            }
        });
        getContentPane().add(tFPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 120, -1));

        tFUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tFUsuario.setDescripcion("Usuario");
        getContentPane().add(tFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Login.png"))); // NOI18N
        panelCurves1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panelCurves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 110));

        jMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsecion.png"))); // NOI18N
        jMSalir.setText("Salir");
        jMSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        verificaAdm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tFPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPassActionPerformed
         verificaAdm();
    }//GEN-LAST:event_tFPassActionPerformed

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        this.setVisible(false);
        Principal obj=new Principal();
        obj.setVisible(true);
        cn.desconectar();
    }//GEN-LAST:event_jMSalirMouseClicked
    
    void verificaAdm(){
     String sql="Select idusuariosadm, nombres, apellidos from usuariosadm where usrname = '"+tFUsuario.getText()+"' and psw = '"+tFPass.getText()+"';";
     boolean ExisteAdm=false;
         try{
             Statement st = cn.getConnection().createStatement(); 
             ResultSet rs = st.executeQuery(sql);
         
            while(rs.next()){
                ExisteAdm=true;       
                idResponsable =rs.getInt(1);
                this.nombre=rs.getString(2)+" "+rs.getString(3);
                JOptionPane.showMessageDialog(null,"Bienvenido "+nombre,"Encargado Aceptado",JOptionPane.WARNING_MESSAGE,this.usrVal);
                Ventana();
            }           
            rs.close();
            st.close();
            cn.desconectar();
        }catch(Exception ex){    }
       if(!ExisteAdm){
         JOptionPane.showMessageDialog(null,"Error al ingresar","Encargado No Valido",JOptionPane.WARNING_MESSAGE,this.usrNVal);
       }
     }
    public void Ventana() throws Exception{
        if(Principal.login==true){
         Administracion adm= new Administracion();
        adm.setVisible(true);
        }else{
            Prestamos prestamos= new Prestamos();
            prestamos.setVisible(true);
        }
     this.setVisible(false);
    }
    
    //Limpia los cuadros de texto
    private void Limpiar(){
            tFUsuario.setText("");
            tFPass.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new loginAdm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(loginAdm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundBackground tFPass;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFUsuario;
    // End of variables declaration//GEN-END:variables
}
