package uai_biblioteca;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class SugerenciasView extends javax.swing.JFrame {
    Conexion cn;
    public SugerenciasView() throws Exception {
        initComponents();
        cn = new Conexion();
        setLocationRelativeTo(null);
        setResizable(false);
        mostrar();
    }

    //icono de la apliccacion
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/libros.png"));
        return retValue;
    }

    //Muestra por defecto la consulta de deudores
    private void mostrar() throws Exception {
        String sql;
        DefaultTableModel Modelo = new DefaultTableModel();
        Modelo.addColumn("SUGERIDO POR:");
        Modelo.addColumn("TITULO");
        Modelo.addColumn("AUTOR");
        Modelo.addColumn("EDITORIAL");
        Modelo.addColumn("EDICION");
        Modelo.addColumn("ID");
        jTable1.setModel(Modelo);
        sql = "SELECT Nombres, Apellidos, Titulo, Autor, Editorial, Edicion, IdSugerencia FROM Sugerencia INNER JOIN Personas WHERE idPersona = IdPersonas;";
        String[] datos = new String[6];
        try {
            Statement st = cn.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1) + " " + rs.getString(2);
                datos[1] = rs.getString(3);
                datos[2] = rs.getString(4);
                datos[3] = rs.getString(5);
                datos[4] = rs.getString(6);
                datos[5] = rs.getString(7);
                Modelo.addRow(datos);

            }
            jTable1.setModel(Modelo);
        } catch (SQLException ex) {
            System.out.println("Error al mostrar:" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Verifica que haya texto en los campos de los libros
    private boolean Libro1Completo() {
        if (tFTitulo1.getText().length() != 0 && tFAutor1.getText().length() != 0 && tFEdicion1.getText().length() != 0 && tFEditorial1.getText().length() != 0 && tFISBN1.getText().length() != 0) {
            return true;
        } else {
            return false;
        }
    }

    //verifica campos completos en el panel de libro 2
    private boolean Libro2Completo() {
        if (tFTitulo2.getText().length() != 0 && tFAutor2.getText().length() != 0 && tFEdicion2.getText().length() != 0 && tFEditorial2.getText().length() != 0 && tFISBN2.getText().length() != 0) {
            return true;
        } else {
            return false;
        }
    }
    //Deshabilita campos del libro 1

    private void OPECampos(String Libro, boolean estado) {
        if (Libro.equals("Libro1")) {
            tFTitulo1.setEnabled(estado);
            tFAutor1.setEnabled(estado);
            tFEdicion1.setEnabled(estado);
            tFEditorial1.setEnabled(estado);
            tFISBN1.setEnabled(estado);
        } else {
            tFTitulo2.setEnabled(estado);
            tFAutor2.setEnabled(estado);
            tFEdicion2.setEnabled(estado);
            tFEditorial2.setEnabled(estado);
            tFISBN2.setEnabled(estado);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buGroup = new javax.swing.ButtonGroup();
        JPMContextual = new javax.swing.JPopupMenu();
        jMEliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPLibro1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tFMatricula = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jPLibro2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tFTitulo2 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        tFAutor2 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        tFEditorial2 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        tFEdicion2 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jCBTitulo2 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        tFISBN2 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jBSalir = new javax.swing.JButton();
        jBFormato = new javax.swing.JButton();
        jPLibro3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tFTitulo1 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        tFAutor1 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        tFEditorial1 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        tFEdicion1 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jCBTitulo1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        tFISBN1 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMSalir = new javax.swing.JMenu();

        jMEliminar.setText("Eliminar");
        jMEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMEliminarMousePressed(evt);
            }
        });
        JPMContextual.add(jMEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control de Sugerencias de Libros");
        setIconImage(getIconImage());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Sugerencias Bibliograficas.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setComponentPopupMenu(JPMContextual);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPLibro1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 204)), "Matricula Del Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Matricula:");

        tFMatricula.setDescripcion("Matricula del alumno");
        tFMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFMatriculaActionPerformed(evt);
            }
        });
        tFMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFMatriculaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPLibro1Layout = new javax.swing.GroupLayout(jPLibro1);
        jPLibro1.setLayout(jPLibro1Layout);
        jPLibro1Layout.setHorizontalGroup(
            jPLibro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLibro1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPLibro1Layout.setVerticalGroup(
            jPLibro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLibro1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLibro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jPLibro2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 204)), "Libro 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Titulo:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Autor:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Editorial:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Edición:");

        tFTitulo2.setDescripcion("Escriba el titulo del libro 2");

        tFAutor2.setDescripcion("Escriba el autor del libro 2");

        tFEditorial2.setDescripcion("Escriba la editorial del libro 2");

        tFEdicion2.setDescripcion("Escriba la edición del libro 2");

        jCBTitulo2.setText("Confirmar");
        jCBTitulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTitulo2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ISBN:");

        tFISBN2.setDescripcion("Escriba el ISBN del libro 2");

        javax.swing.GroupLayout jPLibro2Layout = new javax.swing.GroupLayout(jPLibro2);
        jPLibro2.setLayout(jPLibro2Layout);
        jPLibro2Layout.setHorizontalGroup(
            jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLibro2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPLibro2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCBTitulo2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFEdicion2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(tFEditorial2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFISBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPLibro2Layout.setVerticalGroup(
            jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLibro2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tFTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tFAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFEditorial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tFEdicion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLibro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tFISBN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBTitulo2)
                .addGap(50, 50, 50))
        );

        jBSalir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBSalir.setText("Cancelar");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBFormato.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jBFormato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        jBFormato.setText("Generar Formato");
        jBFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFormatoActionPerformed(evt);
            }
        });

        jPLibro3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(204, 0, 204)), "Libro 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Titulo:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Autor:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Editorial:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Edición:");

        tFTitulo1.setDescripcion("Escriba el titulo del libro 1");

        tFAutor1.setDescripcion("Escriba el autor del libro 1");

        tFEditorial1.setDescripcion("Escriba la editorial del libro 1");

        tFEdicion1.setDescripcion("Escriba la edición del libro 1");

        jCBTitulo1.setText("Confirmar");
        jCBTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTitulo1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("ISBN:");

        tFISBN1.setDescripcion("Escriba el ISBN del libro 1");

        javax.swing.GroupLayout jPLibro3Layout = new javax.swing.GroupLayout(jPLibro3);
        jPLibro3.setLayout(jPLibro3Layout);
        jPLibro3Layout.setHorizontalGroup(
            jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLibro3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPLibro3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCBTitulo1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFEdicion1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFEditorial1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPLibro3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tFISBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPLibro3Layout.setVerticalGroup(
            jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLibro3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tFTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tFAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFEditorial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tFEdicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLibro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tFISBN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBTitulo1)
                .addGap(50, 50, 50))
        );

        jMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsecion.png"))); // NOI18N
        jMSalir.setText("Salir");
        jMSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPLibro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBFormato)
                        .addGap(22, 22, 22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBFormato, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jBSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        try {
            int fila = jTable1.getSelectedRow();
            if (fila >= 0 && jCBTitulo1.isSelected() == false) {
                tFTitulo1.setText(jTable1.getValueAt(fila, 1).toString());
                tFAutor1.setText(jTable1.getValueAt(fila, 2).toString());
                tFEditorial1.setText(jTable1.getValueAt(fila, 3).toString());
                tFEdicion1.setText(jTable1.getValueAt(fila, 4).toString());
                tFISBN1.setText("N/A");

            } else {
                tFTitulo2.setText(jTable1.getValueAt(fila, 1).toString());
                tFAutor2.setText(jTable1.getValueAt(fila, 2).toString());
                tFEditorial2.setText(jTable1.getValueAt(fila, 3).toString());
                tFEdicion2.setText(jTable1.getValueAt(fila, 4).toString());
                tFISBN2.setText("N/A");
            }
        } catch (Exception e) {
            System.out.println("Error al seleccionar fila " + e.getMessage());
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jCBTitulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTitulo2ActionPerformed
        if (!jCBTitulo2.isSelected()) {
            OPECampos("Libro2", true);
        } else if (Libro2Completo()) {
            OPECampos("Libro2", false);
        } else {
            JOptionPane.showMessageDialog(this, "Campos Faltantes", "Debe completar los campos requeridos", JOptionPane.ERROR_MESSAGE);
            jCBTitulo2.setSelected(false);
        }
    }//GEN-LAST:event_jCBTitulo2ActionPerformed

    private void jBFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFormatoActionPerformed
         if (tFMatricula.getText().length() != 0 && jCBTitulo1.isSelected() && jCBTitulo2.isSelected()) {
            ReporteSugerencia(tFMatricula.getText(),loginAdm.idResponsable);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar una matricula y confirmar los libros", "Error al procesar", JOptionPane.WARNING_MESSAGE);
            tFMatricula.requestFocus();
        }
    }//GEN-LAST:event_jBFormatoActionPerformed

    private void jCBTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTitulo1ActionPerformed
        if (!jCBTitulo1.isSelected()) {
            OPECampos("Libro1", true);
        } else if (Libro1Completo()) {
            OPECampos("Libro1", false);
        } else {
            JOptionPane.showMessageDialog(this, "Campos Faltantes", "Debe completar los campos requeridos", JOptionPane.ERROR_MESSAGE);
            jCBTitulo1.setSelected(false);
        }
    }//GEN-LAST:event_jCBTitulo1ActionPerformed

    private void tFMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFMatriculaKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tFMatriculaKeyTyped

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        Limpiar();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jMEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMEliminarMousePressed
        String ID = "";
        try {
            int fila = jTable1.getSelectedRow();
            if (fila >= 0 && jCBTitulo1.isSelected() == false) {
                ID = (jTable1.getValueAt(fila, 5).toString());
            }
        } catch (Exception e) {
            System.out.println("Error al dar clic derecho en fila " + e.getMessage());
        }

        try {
            String sql = "DELETE FROM Sugerencia WHERE idSugerencia ='" + ID + "';";
            Statement st = cn.getConnection().createStatement();
            st.executeUpdate(sql);
            st.close();
            mostrar();

        } catch (Exception e) {
            System.out.println("Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_jMEliminarMousePressed

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        this.setVisible(false);
        cn.desconectar();
    }//GEN-LAST:event_jMSalirMouseClicked

    private void tFMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFMatriculaActionPerformed
        if (tFMatricula.getText().length() != 0 && jCBTitulo1.isSelected() && jCBTitulo2.isSelected()) {
            ReporteSugerencia(tFMatricula.getText(),loginAdm.idResponsable);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar una matricula y confirmar los libros", "Error al procesar", JOptionPane.WARNING_MESSAGE);
            tFMatricula.requestFocus();
        }
    }//GEN-LAST:event_tFMatriculaActionPerformed

    //Limpiar los cuadros de texto
    private void Limpiar() {
        tFTitulo1.setText("");
        tFTitulo2.setText("");
        tFAutor1.setText("");
        tFAutor2.setText("");
        tFEditorial1.setText("");
        tFEditorial2.setText("");
        tFEdicion1.setText("");
        tFEdicion2.setText("");
        tFISBN1.setText("");
        tFISBN2.setText("");
        tFMatricula.setText("");
        jCBTitulo1.setSelected(false);
        jCBTitulo2.setSelected(false);
    }

//Imprime reporte de sugerencia de donacion de titulación
    @SuppressWarnings("unchecked")
    void ReporteSugerencia(String Matricula, int Responsable) {
        try {
            String ruta = "src/reportes/SugerenciaBiblio.jasper";
            Map parametros = new HashMap();
            parametros.put("AUT1", String.valueOf(tFAutor1.getText()));
            parametros.put("TIT1", String.valueOf(tFTitulo1.getText()));
            parametros.put("EDI1", String.valueOf(tFEdicion1.getText()));
            parametros.put("EDITO1", String.valueOf(tFEditorial1.getText()));
            parametros.put("ISBN1", String.valueOf(tFISBN1.getText()));

            parametros.put("AUT2", String.valueOf(tFAutor2.getText()));
            parametros.put("TIT2", String.valueOf(tFTitulo2.getText()));
            parametros.put("EDI2", String.valueOf(tFEdicion2.getText()));
            parametros.put("EDITO2", String.valueOf(tFEditorial2.getText()));
            parametros.put("ISBN2", String.valueOf(tFISBN2.getText()));

            parametros.put("valormatricula", Matricula);
            parametros.put("Responsable", Responsable);

            JasperReport jr = (JasperReport) JRLoader.loadObjectFromFile(ruta);
            JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn.getConnection());
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.setTitle("Sugerencia de donación de libros para titulación");

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SugerenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SugerenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SugerenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SugerenciasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SugerenciasView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SugerenciasView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu JPMContextual;
    private javax.swing.ButtonGroup buGroup;
    private javax.swing.JButton jBFormato;
    private javax.swing.JButton jBSalir;
    private javax.swing.JCheckBox jCBTitulo1;
    private javax.swing.JCheckBox jCBTitulo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMEliminar;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPLibro1;
    private javax.swing.JPanel jPLibro2;
    private javax.swing.JPanel jPLibro3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFAutor1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFAutor2;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFEdicion1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFEdicion2;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFEditorial1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFEditorial2;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFISBN1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFISBN2;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFMatricula;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFTitulo1;
    private org.edisoncor.gui.textField.TextFieldRoundBackground tFTitulo2;
    // End of variables declaration//GEN-END:variables
}
